version: '2'

services:
  mongo:
    image: mongo:4
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_MASTER_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_MASTER_PASSWORD}
