service: serverless-mongodb-backend
frameworkVersion: '=1.23.X'

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE, 'dev'}
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:profile, 'default'}
  apiKeys:
    - ${self:provider.stage}-api
  stackName: ${env:CF_APP_STACKNAME, 'api'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:List*
        - ec2:Describe*
        - ec2:RegisterImage
        - ec2:DeregisterImage
        - ssm:GetParametersByPath
        - kms:Decrypt
      Resource: '*'
  environment:
    NODE_ENV: ${self:custom.NodeEnvByStage.${self:provider.stage}}
    PARAM_PATH: ${env:PARAM_PATH, '/${self:provider.stackName}/${self:provider.stage}'}
    DB_HOST: ${cf:${env:CF_DB_STACK, 'mongodb-${env:STAGE}'}.DbHost}
    DB_NAME: ${env:DB_NAME, 'db'}


package:
 include:
   - node_modules/**
   - dist/**

custom:
  NodeEnvByStage:
    dev: development
    test: test
    prod: production


functions:
  mongodbCrud:
    handler: dist/index.crud
    description: Handles Create, Read, Update, and Destroy operations for MongoDB
    events:
      - http:
          path: /
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: put
          cors: true
    private: true # enforces the use of x-api-key in header
    environment:
